### ISSUE TITLE
Incompatibility with devise gem. NoMethodError in Users::SessionsController#new

### ISSUE THREAD

**Issue by pardeyke** [joshmn/hotflash#1]
I had my app running with turbo_flash but after the update to hotflash it breaks every time a devise controller is used. Even disabling hotflash for each devise controller didn't fix it.

It is enough to add the gem in the Gemfile like
`gem "hot_flash", "~> 1.0"`

When trying to login I get:
```
NoMethodError in Users::SessionsController#new
private method `render' called for #<Users::SessionsController:0x00000000014190>
```

last lines from Full Trace:
```
[responders (3.1.0) lib/action_controller/responder.rb:245:in `default_render' ](http://packlis.tr:3000/users/sign_in#)
[responders (3.1.0) lib/action_controller/responder.rb:175:in `to_html' ](http://packlis.tr:3000/users/sign_in#)
[responders (3.1.0) lib/action_controller/responder.rb:168:in `respond' ](http://packlis.tr:3000/users/sign_in#)
[responders (3.1.0) lib/action_controller/responder.rb:161:in `call' ](http://packlis.tr:3000/users/sign_in#)
[responders (3.1.0) lib/action_controller/respond_with.rb:216:in `respond_with' ](http://packlis.tr:3000/users/sign_in#)
[devise (4.9.2) app/controllers/devise/sessions_controller.rb:14:in `new' ](http://packlis.tr:3000/users/sign_in#)
[actionpack (7.0.7.2) lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action' ](http://packlis.tr:3000/users/sign_in#)
actionpack (7.0.7.2) lib/abstract_controller/base.rb:215:in `process_action'
```

**Comment by joshmn** [comment]
Ah shoot, you're right! I fixed this in 1.1. Feel free to `bundle update hot_flash` :)
